import "./globals.css";
import "@css/flaticon.min.css";
import "@css/fontawesome-5.14.0.min.css";
import "@css/bootstrap.min.css";
import "@css/magnific-popup.min.css";
import "@css/nice-select.min.css";
import "@css/aos.css";
import "@css/slick.min.css";
import "@css/style.css";
import ToastProvider from "@/components/ToastProvider";
import { AppContextProvider } from "@/app/context/AppContext";


export const metadata = {
  title: "Ridda - Web Design & SEO React NextJS Template",
  description: "Generated by ridda - Web Design & SEO React NextJS Template",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppContextProvider>
        {children}
        <ToastProvider /> 
        </AppContextProvider>
       <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
      </body>
    </html>
  );
}
